- menu_name: "Service"

- name: "Kontakt"
  url: "/de/kontakt"
  title: "Kontakt"
  
- name: "Impressum und Datenschutz"
  url: "/de/impressum"
  title: "Impressum und Datenschutz"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"

- name: "Atom"
  url: "/atom.xml"
  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
